import pandas as pd
import json

df = pd.read_csv("URLS.csv")

excelData = []

for index, row in df.iterrows():
    excelData.append({
        "type": row['type'],
        "id": row['id'],
        "data": {
            'name': row['name'],
            'url': row['url']
        }
    })

ldif = {
        "connectorType": "leanix",
        "connectorId": "leanix-pandasCSV",
        "connectorVersion": "1.0.0",
        "processingDirection": "inbound",
        "processingMode": "partial",
        "lxVersion": "1.0.0",
        "description": "LDIF Generated by PANDAS CSV data",
        "content": excelData}

print ("Writing output to output.json")
f = open("output.json", "w")
f.write(json.dumps(ldif, indent=2))
f.close()
print ("Done")
