import logging
import csv
import json


with open("URLS.csv") as df:
    try:
        logging.info(f'Parsing csv file: {df.name}')
        reader = csv.DictReader(df, delimiter=';')

    except Exception as e:
        logging.error(f'Failed to load csv file: {e}')

excelData = []

for index, row in reader:
    excelData.append({
        "type": row['type'],
        "id": row['id'],
        "data": {
            'name': row['name'],
            'url': row['url']
        }
    })

ldif = {
        "connectorType": "leanix",
        "connectorId": "leanix-pandasCSV",
        "connectorVersion": "1.0.0",
        "processingDirection": "inbound",
        "processingMode": "partial",
        "lxVersion": "1.0.0",
        "description": "LDIF Generated by PANDAS CSV data",
        "content": excelData}

logging.info("Writing output to output.json")
f = open("output.json", "w")
f.write(json.dumps(ldif, indent=2))
f.close()
logging.info("Done")
